import React, { createContext, useContext, useState } from "react";

// ── Language list ─────────────────────────────────────────────
export const LANGUAGES = [
  { code: "en", name: "English",    native: "English",   flag: "🇬🇧" },
  { code: "hi", name: "Hindi",      native: "हिंदी",      flag: "🇮🇳" },
  { code: "mr", name: "Marathi",    native: "मराठी",      flag: "🇮🇳" },
  { code: "gu", name: "Gujarati",   native: "ગુજરાતી",    flag: "🇮🇳" },
  { code: "ta", name: "Tamil",      native: "தமிழ்",      flag: "🇮🇳" },
  { code: "te", name: "Telugu",     native: "తెలుగు",     flag: "🇮🇳" },
  { code: "kn", name: "Kannada",    native: "ಕನ್ನಡ",      flag: "🇮🇳" },
  { code: "bn", name: "Bengali",    native: "বাংলা",      flag: "🇮🇳" },
  { code: "pa", name: "Punjabi",    native: "ਪੰਜਾਬੀ",     flag: "🇮🇳" },
  { code: "ml", name: "Malayalam",  native: "മലയാളം",     flag: "🇮🇳" },
  { code: "or", name: "Odia",       native: "ଓଡ଼ିଆ",       flag: "🇮🇳" },
  { code: "ur", name: "Urdu",       native: "اردو",       flag: "🇮🇳" },
];

// ── All translations ──────────────────────────────────────────
// Simple words — no accounting jargon
// "Uneducated shopkeeper should understand"
const T = {
  en: {
    // Nav — simple words
    dashboard:"Home", sales:"Sales", purchases:"Purchase",
    inventory:"Stock", expenses:"Spending", customers:"Customers",
    khata:"Credit Book", cashBook:"Cash", gstInvoice:"Bill / Invoice",
    gstReturns:"GST Filing", profitLoss:"Profit & Loss",
    balanceSheet:"Balance Sheet", aiAdvisor:"Ask AI",
    // Dashboard
    businessDashboard:"My Business",
    thisMonth:"This Month", estimatedPL:"Money Earned",
    fullPL:"Full Details", aiInsights:"AI Tips",
    recentSales:"Recent Sales", allSales:"See All Sales →",
    topProducts:"Best Selling Items", salesChart:"Sales - Last 30 Days",
    expensesChart:"Money Spent This Month",
    monthlySales:"Monthly Sales - 6 Months",
    healthScore:"Business Score",
    revenue:"Income", profit:"Profit",
    // Health score — simple language
    netMargin:"Profit Percentage",
    khataControl:"Credit Given",
    cashGen:"Cash in Hand",
    expControl:"Spending Control",
    invHealth:"Stock Status",
    // Actions
    newSale:"Add Sale", newInvoice:"Make Bill",
    addEntry:"Add Entry", addItem:"+ Add Item",
    save:"Save", cancel:"Back", print:"Print",
    whatsapp:"Send on WhatsApp", markPaid:"Mark as Paid",
    remind:"Remind Customer",
    // Labels
    customer:"Customer", amount:"Amount ₹", date:"Date",
    total:"Total", qty:"How Many", rate:"Price",
    grandTotal:"Final Total", cashIn:"Cash Received",
    cashOut:"Cash Paid", openingBal:"Opening Cash",
    closingBal:"Closing Cash",
    // Status
    noSales:"No sales added yet. Add your first sale!",
    noExpenses:"No spending added yet",
    noItems:"No stock added. Add your products!",
    loading:"Please wait...", saved:"Saved!",
    goodMorning:"Good Morning",
    salesEntry:"Sales Entry", totalSalesLabel:"Total Sales", numSalesLabel:"Number of Sales", optional:"(optional)", itemsLabel:"Items", notesPlaceholder:"Any notes about this sale", saving:"Saving...", searchCustomerPh:"Search by customer name", confirmDeleteSale:"Delete this sale?", deletedMsg:"Deleted!", errorMsg:"Something went wrong. Try again.", walkIn:"Walk-in", itemNamePh:"Item name", pricePh:"Price", noSalesEmptyMsg:"No sales yet. Add your first sale above.",
    notes:"Notes",
    noRecordsYet:"Nothing here yet", editItem:"Edit", addNew:"+ Add", update:"Update",
    askPlaceholder:"Ask anything about your business…",
    salesThisMonth:"Sales This Month", estProfit:"Est. Profit",
    inProfitMsg:"You're in profit", notProfitMsg:"Spending is more than earning",
    transactionsWord:"sales made", stockItemsWord:"items in stock",
    analysing:"Checking...", lowStockMsg:"items running low",
    view:"View", updateStock:"Update Stock", logExpense:"Log Expense",
    addCustomer:"Add Customer", payment:"Payment Type",
    thisMonthSub:"this month",
    // Greeting
    welcome:"Welcome to Business Vahi",
    tagline:"Simple accounts for your business",
    startFree:"Start Free",
    login:"Login",
    signOut:"Sign Out",
    more:"More",
    selectLanguage:"Choose Language",
    changeLanguage:"Language",
  },

  hi: {
    dashboard:"होम", sales:"बिक्री", purchases:"खरीदारी",
    inventory:"माल / स्टॉक", expenses:"खर्चा", customers:"ग्राहक",
    khata:"उधार खाता", cashBook:"नकदी", gstInvoice:"बिल / रसीद",
    gstReturns:"GST भरना", profitLoss:"नफ़ा नुकसान",
    balanceSheet:"हिसाब किताब", aiAdvisor:"AI से पूछें",
    businessDashboard:"मेरा कारोबार",
    thisMonth:"इस महीने", estimatedPL:"कमाई",
    fullPL:"पूरी जानकारी", aiInsights:"AI सलाह",
    recentSales:"हाल की बिक्री", allSales:"सारी बिक्री देखें →",
    topProducts:"ज़्यादा बिकने वाला माल", salesChart:"बिक्री - पिछले 30 दिन",
    expensesChart:"इस महीने का खर्चा", monthlySales:"6 महीने की बिक्री",
    healthScore:"कारोबार का स्कोर",
    revenue:"आमदनी", profit:"नफ़ा",
    netMargin:"नफ़े का प्रतिशत", khataControl:"उधार दिया",
    cashGen:"हाथ में नकदी", expControl:"खर्चा नियंत्रण",
    invHealth:"माल की स्थिति",
    newSale:"बिक्री जोड़ें", newInvoice:"बिल बनाएं",
    addEntry:"एंट्री जोड़ें", addItem:"+ माल जोड़ें",
    save:"सेव करें", cancel:"वापस जाएं", print:"प्रिंट करें",
    whatsapp:"WhatsApp पर भेजें", markPaid:"पैसा मिल गया",
    remind:"याद दिलाएं",
    customer:"ग्राहक", amount:"रकम ₹", date:"तारीख",
    total:"कुल", qty:"कितना", rate:"भाव",
    grandTotal:"कुल रकम", cashIn:"नकदी मिली",
    cashOut:"नकदी दी", openingBal:"शुरू की नकदी",
    closingBal:"बची हुई नकदी",
    noSales:"अभी कोई बिक्री नहीं। पहली बिक्री जोड़ें!",
    noExpenses:"अभी कोई खर्चा नहीं",
    noItems:"माल नहीं जोड़ा। अपना माल जोड़ें!",
    loading:"थोड़ा रुकें...", saved:"सेव हो गया!",
    goodMorning:"नमस्ते",
    salesEntry:"बिक्री दर्ज करें", totalSalesLabel:"कुल बिक्री", numSalesLabel:"कुल बिक्री संख्या", optional:"(वैकल्पिक)", itemsLabel:"सामान", notesPlaceholder:"इस बिक्री के बारे में कुछ लिखें", saving:"सेव हो रहा है...", searchCustomerPh:"ग्राहक के नाम से खोजें", confirmDeleteSale:"क्या इस बिक्री को हटाएं?", deletedMsg:"हट गया!", errorMsg:"कुछ गलत हो गया। फिर से कोशिश करें।", walkIn:"सीधा ग्राहक", itemNamePh:"सामान का नाम", pricePh:"भाव", noSalesEmptyMsg:"अभी कोई बिक्री नहीं। ऊपर पहली बिक्री जोड़ें।",
    notes:"टिप्पणी",
    noRecordsYet:"अभी कुछ नहीं है", editItem:"बदलें", addNew:"+ जोड़ें", update:"अपडेट करें",
    askPlaceholder:"अपने कारोबार के बारे में कुछ भी पूछें...",
    salesThisMonth:"इस महीने बिक्री", estProfit:"कमाई",
    inProfitMsg:"आप नफ़े में हैं", notProfitMsg:"खर्चा कमाई से ज़्यादा है",
    transactionsWord:"बिक्री हुई", stockItemsWord:"माल स्टॉक में",
    analysing:"जांच रहे हैं...", lowStockMsg:"माल कम हो रहा है",
    view:"देखें", updateStock:"स्टॉक अपडेट करें", logExpense:"खर्च लिखें",
    addCustomer:"ग्राहक जोड़ें", payment:"पेमेंट टाइप",
    thisMonthSub:"इस महीने",
    welcome:"Business Vahi में आपका स्वागत है",
    tagline:"आपके कारोबार का आसान हिसाब",
    startFree:"मुफ़्त शुरू करें",
    login:"लॉगिन", signOut:"बाहर जाएं",
    more:"और", selectLanguage:"भाषा चुनें",
    changeLanguage:"भाषा",
  },

  mr: {
    dashboard:"होम", sales:"विक्री", purchases:"खरेदी",
    inventory:"माल / स्टॉक", expenses:"खर्च", customers:"ग्राहक",
    khata:"उधारी खाते", cashBook:"रोख", gstInvoice:"बिल / पावती",
    gstReturns:"GST भरणे", profitLoss:"नफा तोटा",
    balanceSheet:"हिशेब", aiAdvisor:"AI ला विचारा",
    businessDashboard:"माझा व्यवसाय",
    thisMonth:"या महिन्यात", estimatedPL:"कमाई",
    fullPL:"सर्व तपशील", aiInsights:"AI सल्ला",
    recentSales:"अलीकडील विक्री", allSales:"सर्व विक्री पहा →",
    topProducts:"जास्त विकले जाणारे माल", salesChart:"विक्री - मागील 30 दिवस",
    expensesChart:"या महिन्यातील खर्च", monthlySales:"6 महिन्यांची विक्री",
    healthScore:"व्यवसायाचा स्कोर",
    revenue:"उत्पन्न", profit:"नफा",
    netMargin:"नफ्याची टक्केवारी", khataControl:"उधारी दिली",
    cashGen:"हातात रोख", expControl:"खर्च नियंत्रण",
    invHealth:"मालाची स्थिती",
    newSale:"विक्री जोडा", newInvoice:"बिल बनवा",
    addEntry:"नोंद जोडा", addItem:"+ माल जोडा",
    save:"जतन करा", cancel:"मागे जा", print:"प्रिंट करा",
    whatsapp:"WhatsApp वर पाठवा", markPaid:"पैसे मिळाले",
    remind:"आठवण करा",
    customer:"ग्राहक", amount:"रक्कम ₹", date:"तारीख",
    total:"एकूण", qty:"किती", rate:"भाव",
    grandTotal:"एकूण रक्कम", cashIn:"रोख मिळाली",
    cashOut:"रोख दिली", openingBal:"सुरुवातीची रोख",
    closingBal:"शिल्लक रोख",
    noSales:"अजून विक्री नाही. पहिली विक्री जोडा!",
    noExpenses:"अजून खर्च नाही",
    noItems:"माल जोडला नाही. आपला माल जोडा!",
    loading:"थांबा...", saved:"जतन झाले!",
    goodMorning:"नमस्कार",
    salesEntry:"विक्री नोंद", totalSalesLabel:"एकूण विक्री", numSalesLabel:"एकूण विक्री संख्या", optional:"(ऐच्छिक)", itemsLabel:"माल", notesPlaceholder:"या विक्रीबद्दल काही लिहा", saving:"जतन होत आहे...", searchCustomerPh:"ग्राहकाच्या नावाने शोधा", confirmDeleteSale:"ही विक्री काढायची का?", deletedMsg:"काढले!", errorMsg:"काहीतरी चूक झाली. पुन्हा प्रयत्न करा.", walkIn:"थेट ग्राहक", itemNamePh:"मालाचे नाव", pricePh:"भाव", noSalesEmptyMsg:"अजून विक्री नाही. वर पहिली विक्री जोडा.",
    notes:"टीप",
    noRecordsYet:"अजून काही नाही", editItem:"बदला", addNew:"+ जोडा", update:"अपडेट करा",
    askPlaceholder:"आपल्या व्यवसायाबद्दल काहीही विचारा...",
    salesThisMonth:"या महिन्यात विक्री", estProfit:"अंदाजे नफा",
    inProfitMsg:"तुम्ही नफ्यात आहात", notProfitMsg:"खर्च कमाईपेक्षा जास्त आहे",
    transactionsWord:"विक्री झाली", stockItemsWord:"माल स्टॉकमध्ये",
    analysing:"तपासत आहोत...", lowStockMsg:"माल कमी होत आहे",
    view:"पहा", updateStock:"स्टॉक अपडेट करा", logExpense:"खर्च लिहा",
    addCustomer:"ग्राहक जोडा", payment:"पैसे भरण्याची पद्धत",
    thisMonthSub:"या महिन्यात",
    welcome:"Business Vahi मध्ये आपले स्वागत आहे",
    tagline:"आपल्या व्यवसायाचा सोपा हिशेब",
    startFree:"मोफत सुरू करा",
    login:"लॉगिन", signOut:"बाहेर जा",
    more:"अधिक", selectLanguage:"भाषा निवडा",
    changeLanguage:"भाषा",
  },

  gu: {
    dashboard:"હોમ", sales:"વેચાણ", purchases:"ખરીદી",
    inventory:"માલ / સ્ટોક", expenses:"ખર્ચ", customers:"ગ્રાહક",
    khata:"ઉધાર ખાતું", cashBook:"રોકડ", gstInvoice:"બિલ / રસીદ",
    gstReturns:"GST ભરવો", profitLoss:"નફો નુકસાન",
    balanceSheet:"હિસાબ", aiAdvisor:"AI ને પૂછો",
    businessDashboard:"મારો ધંધો",
    thisMonth:"આ મહિને", estimatedPL:"કમાણી",
    fullPL:"સંપૂર્ણ વિગત", aiInsights:"AI સલાહ",
    recentSales:"તાજેતરના વેચાણ", allSales:"બધા વેચાણ જુઓ →",
    topProducts:"સૌથી વધુ વેચાતો માલ", salesChart:"વેચાણ - છેલ્લા 30 દિવસ",
    expensesChart:"આ મહિને ખર્ચ", monthlySales:"6 મહિનાનું વેચાણ",
    healthScore:"ધંધાનો સ્કોર",
    revenue:"આવક", profit:"નફો",
    netMargin:"નફાની ટકાવારી", khataControl:"ઉધાર આપ્યો",
    cashGen:"હાથમાં રોકડ", expControl:"ખર્ચ નિયંત્રણ",
    invHealth:"માલની સ્થિતિ",
    newSale:"વેચાણ ઉમેરો", newInvoice:"બિલ બનાવો",
    addEntry:"નોંધ ઉમેરો", addItem:"+ માલ ઉમેરો",
    save:"સાચવો", cancel:"પાછા જાઓ", print:"પ્રિન્ટ કરો",
    whatsapp:"WhatsApp પર મોકલો", markPaid:"પૈસા મળ્યા",
    remind:"યાદ અપાવો",
    customer:"ગ્રાહક", amount:"રકમ ₹", date:"તારીખ",
    total:"કુલ", qty:"કેટલું", rate:"ભાવ",
    grandTotal:"કુલ રકમ", cashIn:"રોકડ મળી",
    cashOut:"રોકડ આપી", openingBal:"શરૂઆતની રોકડ",
    closingBal:"બાકી રોકડ",
    noSales:"હજુ વેચાણ નથી. પ્રથમ વેચાણ ઉમેરો!",
    noExpenses:"હજુ ખર્ચ નથી",
    noItems:"માલ ઉમેર્યો નથી. તમારો માલ ઉમેરો!",
    loading:"રાહ જુઓ...", saved:"સાચવ્યું!",
    goodMorning:"નમસ્તે",
    salesEntry:"વેચાણ નોંધ", totalSalesLabel:"કુલ વેચાણ", numSalesLabel:"કુલ વેચાણ સંખ્યા", optional:"(વૈકલ્પિક)", itemsLabel:"માલ", notesPlaceholder:"આ વેચાણ વિશે કંઈ લખો", saving:"સાચવાઈ રહ્યું છે...", searchCustomerPh:"ગ્રાહકના નામથી શોધો", confirmDeleteSale:"આ વેચાણ કાઢી નાખવું?", deletedMsg:"કાઢી નાખ્યું!", errorMsg:"કંઈક ખોટું થયું. ફરી પ્રયત્ન કરો.", walkIn:"સીધો ગ્રાહક", itemNamePh:"માલનું નામ", pricePh:"ભાવ", noSalesEmptyMsg:"હજુ વેચાણ નથી. ઉપર પ્રથમ વેચાણ ઉમેરો.",
    notes:"નોંધ",
    noRecordsYet:"હજુ કંઈ નથી", editItem:"બદલો", addNew:"+ ઉમેરો", update:"અપડેટ કરો",
    askPlaceholder:"તમારા ધંધા વિશે કંઈપણ પૂછો...",
    salesThisMonth:"આ મહિને વેચાણ", estProfit:"અંદાજિત નફો",
    inProfitMsg:"તમે નફામાં છો", notProfitMsg:"ખર્ચ કમાણી કરતાં વધારે છે",
    transactionsWord:"વેચાણ થયું", stockItemsWord:"માલ સ્ટોકમાં",
    analysing:"તપાસી રહ્યા છીએ...", lowStockMsg:"માલ ઓછો થઈ રહ્યો છે",
    view:"જુઓ", updateStock:"સ્ટોક અપડેટ કરો", logExpense:"ખર્ચ લખો",
    addCustomer:"ગ્રાહક ઉમેરો", payment:"ચુકવણીની રીત",
    thisMonthSub:"આ મહિને",
    welcome:"Business Vahi માં આપનું સ્વાગત છે",
    tagline:"તમારા ધંધાનો સરળ હિસાબ",
    startFree:"મફત શરૂ કરો",
    login:"લૉગિન", signOut:"બહાર જાઓ",
    more:"વધુ", selectLanguage:"ભાષા પસંદ કરો",
    changeLanguage:"ભાષા",
  },

  ta: {
    dashboard:"முகப்பு", sales:"விற்பனை", purchases:"கொள்முதல்",
    inventory:"பொருட்கள்", expenses:"செலவு", customers:"வாடிக்கையாளர்",
    khata:"கடன் புத்தகம்", cashBook:"பணம்", gstInvoice:"பில் / ரசீது",
    gstReturns:"GST தாக்கல்", profitLoss:"லாப நஷ்டம்",
    balanceSheet:"கணக்கு", aiAdvisor:"AI கேளுங்கள்",
    businessDashboard:"என் வியாபாரம்",
    thisMonth:"இம்மாதம்", estimatedPL:"சம்பாதிப்பு",
    fullPL:"முழு விவரம்", aiInsights:"AI ஆலோசனை",
    recentSales:"சமீபத்திய விற்பனை", allSales:"அனைத்து விற்பனை →",
    topProducts:"அதிகம் விற்கும் பொருட்கள்", salesChart:"விற்பனை - கடந்த 30 நாட்கள்",
    expensesChart:"இம்மாத செலவு", monthlySales:"6 மாத விற்பனை",
    healthScore:"வியாபார மதிப்பெண்",
    revenue:"வருமானம்", profit:"லாபம்",
    netMargin:"லாப சதவீதம்", khataControl:"கடன் கொடுத்தது",
    cashGen:"கையில் பணம்", expControl:"செலவு கட்டுப்பாடு",
    invHealth:"பொருட்கள் நிலை",
    newSale:"விற்பனை சேர்", newInvoice:"பில் உருவாக்கு",
    addEntry:"பதிவு சேர்", addItem:"+ பொருள் சேர்",
    save:"சேமி", cancel:"திரும்பு", print:"அச்சிடு",
    whatsapp:"WhatsApp-ல் அனுப்பு", markPaid:"பணம் கிடைத்தது",
    remind:"நினைவூட்டு",
    customer:"வாடிக்கையாளர்", amount:"தொகை ₹", date:"தேதி",
    total:"மொத்தம்", qty:"எத்தனை", rate:"விலை",
    grandTotal:"மொத்த தொகை", cashIn:"பணம் வந்தது",
    cashOut:"பணம் சென்றது", openingBal:"தொடக்க பணம்",
    closingBal:"மீதி பணம்",
    noSales:"இன்னும் விற்பனை இல்லை. முதல் விற்பனை சேருங்கள்!",
    noExpenses:"இன்னும் செலவு இல்லை",
    noItems:"பொருட்கள் சேர்க்கவில்லை!",
    loading:"காத்திருங்கள்...", saved:"சேமிக்கப்பட்டது!",
    goodMorning:"வணக்கம்",
    salesEntry:"விற்பனை பதிவு", totalSalesLabel:"மொத்த விற்பனை", numSalesLabel:"மொத்த விற்பனை எண்ணிக்கை", optional:"(விருப்பம்)", itemsLabel:"பொருட்கள்", notesPlaceholder:"இந்த விற்பனை பற்றி எழுதுங்கள்", saving:"சேமிக்கிறது...", searchCustomerPh:"வாடிக்கையாளர் பெயரால் தேடு", confirmDeleteSale:"இந்த விற்பனையை நீக்கவா?", deletedMsg:"நீக்கப்பட்டது!", errorMsg:"ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.", walkIn:"நேரடி வாடிக்கையாளர்", itemNamePh:"பொருளின் பெயர்", pricePh:"விலை", noSalesEmptyMsg:"இன்னும் விற்பனை இல்லை. மேலே முதல் விற்பனையைச் சேர்க்கவும்.",
    notes:"குறிப்பு",
    noRecordsYet:"இன்னும் ஒன்றும் இல்லை", editItem:"மாற்று", addNew:"+ சேர்", update:"புதுப்பி",
    askPlaceholder:"உங்கள் வியாபாரத்தைப் பற்றி எதுவும் கேளுங்கள்...",
    salesThisMonth:"இம்மாத விற்பனை", estProfit:"கணக்கிடப்பட்ட லாபம்",
    inProfitMsg:"நீங்கள் லாபத்தில் இருக்கிறீர்கள்", notProfitMsg:"செலவு வருமானத்தை விட அதிகம்",
    transactionsWord:"விற்பனை ஆனது", stockItemsWord:"பொருட்கள் ஸ்டாக்கில்",
    analysing:"சரிபார்க்கிறோம்...", lowStockMsg:"பொருட்கள் குறைந்து வருகிறது",
    view:"பார்", updateStock:"ஸ்டாக் புதுப்பி", logExpense:"செலவு எழுது",
    addCustomer:"வாடிக்கையாளர் சேர்", payment:"பணம் செலுத்தும் முறை",
    thisMonthSub:"இம்மாதம்",
    welcome:"Business Vahi-க்கு வரவேற்கிறோம்",
    tagline:"உங்கள் வியாபாரத்தின் எளிய கணக்கு",
    startFree:"இலவசமாக தொடங்கு",
    login:"உள்நுழை", signOut:"வெளியேறு",
    more:"மேலும்", selectLanguage:"மொழி தேர்வு",
    changeLanguage:"மொழி",
  },

  te: {
    dashboard:"హోమ్", sales:"అమ్మకాలు", purchases:"కొనుగోలు",
    inventory:"సరుకు", expenses:"ఖర్చులు", customers:"కస్టమర్లు",
    khata:"అప్పుల పుస్తకం", cashBook:"నగదు", gstInvoice:"బిల్లు",
    gstReturns:"GST దాఖలు", profitLoss:"లాభనష్టాలు",
    balanceSheet:"లెక్కలు", aiAdvisor:"AI అడగండి",
    businessDashboard:"నా వ్యాపారం",
    thisMonth:"ఈ నెల", estimatedPL:"సంపాదన",
    fullPL:"పూర్తి వివరాలు", aiInsights:"AI సూచనలు",
    recentSales:"ఇటీవల అమ్మకాలు", allSales:"అన్ని అమ్మకాలు →",
    topProducts:"ఎక్కువ అమ్ముడైన సరుకు", salesChart:"అమ్మకాలు - 30 రోజులు",
    expensesChart:"ఈ నెల ఖర్చులు", monthlySales:"6 నెలల అమ్మకాలు",
    healthScore:"వ్యాపార స్కోర్",
    revenue:"ఆదాయం", profit:"లాభం",
    netMargin:"లాభం శాతం", khataControl:"అప్పు ఇచ్చింది",
    cashGen:"చేతిలో నగదు", expControl:"ఖర్చు నియంత్రణ",
    invHealth:"సరుకు స్థితి",
    newSale:"అమ్మకం చేర్చు", newInvoice:"బిల్లు తయారు",
    addEntry:"నమోదు చేర్చు", addItem:"+ సరుకు చేర్చు",
    save:"సేవ్ చేయి", cancel:"వెనుకకు", print:"ప్రింట్",
    whatsapp:"WhatsApp లో పంపు", markPaid:"డబ్బు వచ్చింది",
    remind:"గుర్తు చేయి",
    customer:"కస్టమర్", amount:"మొత్తం ₹", date:"తేదీ",
    total:"మొత్తం", qty:"ఎంత", rate:"ధర",
    grandTotal:"మొత్తం రొక్కం", cashIn:"నగదు వచ్చింది",
    cashOut:"నగదు వెళ్ళింది", openingBal:"మొదటి నగదు",
    closingBal:"మిగిలిన నగదు",
    noSales:"ఇంకా అమ్మకాలు లేవు!",
    noExpenses:"ఇంకా ఖర్చులు లేవు",
    noItems:"సరుకు చేర్చలేదు!",
    loading:"వేచి ఉండండి...", saved:"సేవ్ అయింది!",
    goodMorning:"నమస్కారం",
    salesEntry:"అమ్మకం నమోదు", totalSalesLabel:"మొత్తం అమ్మకాలు", numSalesLabel:"మొత్తం అమ్మకాల సంఖ్య", optional:"(ఐచ్ఛికం)", itemsLabel:"సరుకు", notesPlaceholder:"ఈ అమ్మకం గురించి రాయండి", saving:"సేవ్ అవుతోంది...", searchCustomerPh:"కస్టమర్ పేరుతో వెతకండి", confirmDeleteSale:"ఈ అమ్మకం తీసివేయాలా?", deletedMsg:"తీసివేయబడింది!", errorMsg:"ఏదో తప్పు జరిగింది. మళ్ళీ ప్రయత్నించండి.", walkIn:"నేరుగా కస్టమర్", itemNamePh:"సరుకు పేరు", pricePh:"ధర", noSalesEmptyMsg:"ఇంకా అమ్మకాలు లేవు. పైన మొదటి అమ్మకం చేర్చండి.",
    notes:"గమనిక",
    noRecordsYet:"ఇంకా ఏమీ లేదు", editItem:"మార్చు", addNew:"+ చేర్చు", update:"అప్‌డేట్ చేయి",
    askPlaceholder:"మీ వ్యాపారం గురించి ఏదైనా అడగండి...",
    salesThisMonth:"ఈ నెల అమ్మకాలు", estProfit:"అంచనా లాభం",
    inProfitMsg:"మీరు లాభంలో ఉన్నారు", notProfitMsg:"ఖర్చు సంపాదన కంటే ఎక్కువ",
    transactionsWord:"అమ్మకాలు జరిగాయి", stockItemsWord:"సరుకు స్టాక్‌లో",
    analysing:"పరిశీలిస్తున్నాం...", lowStockMsg:"సరుకు తక్కువగా ఉంది",
    view:"చూడు", updateStock:"స్టాక్ అప్‌డేట్ చేయి", logExpense:"ఖర్చు రాయి",
    addCustomer:"కస్టమర్ చేర్చు", payment:"చెల్లింపు విధానం",
    thisMonthSub:"ఈ నెల",
    welcome:"Business Vahi కి స్వాగతం",
    tagline:"మీ వ్యాపారం సులభమైన లెక్కలు",
    startFree:"ఉచితంగా ప్రారంభించు",
    login:"లాగిన్", signOut:"బయటకు వెళ్ళు",
    more:"మరిన్ని", selectLanguage:"భాష ఎంచుకో",
    changeLanguage:"భాష",
  },

  kn: {
    dashboard:"ಮುಖಪುಟ", sales:"ಮಾರಾಟ", purchases:"ಖರೀದಿ",
    inventory:"ಸರಕು", expenses:"ಖರ್ಚು", customers:"ಗ್ರಾಹಕರು",
    khata:"ಸಾಲ ಪುಸ್ತಕ", cashBook:"ನಗದು", gstInvoice:"ಬಿಲ್ / ರಶೀತಿ",
    gstReturns:"GST ಸಲ್ಲಿಕೆ", profitLoss:"ಲಾಭ ನಷ್ಟ",
    balanceSheet:"ಲೆಕ್ಕ", aiAdvisor:"AI ಕೇಳಿ",
    businessDashboard:"ನನ್ನ ವ್ಯವಹಾರ",
    thisMonth:"ಈ ತಿಂಗಳು", estimatedPL:"ಗಳಿಕೆ",
    fullPL:"ಸಂಪೂರ್ಣ ವಿವರ", aiInsights:"AI ಸಲಹೆ",
    recentSales:"ಇತ್ತೀಚಿನ ಮಾರಾಟ", allSales:"ಎಲ್ಲ ಮಾರಾಟ →",
    topProducts:"ಹೆಚ್ಚು ಮಾರಾಟವಾದ ಸರಕು", salesChart:"ಮಾರಾಟ - 30 ದಿನ",
    expensesChart:"ಈ ತಿಂಗಳ ಖರ್ಚು", monthlySales:"6 ತಿಂಗಳ ಮಾರಾಟ",
    healthScore:"ವ್ಯವಹಾರ ಸ್ಕೋರ್",
    revenue:"ಆದಾಯ", profit:"ಲಾಭ",
    netMargin:"ಲಾಭದ ಶೇಕಡಾ", khataControl:"ಸಾಲ ಕೊಟ್ಟದ್ದು",
    cashGen:"ಕೈಯಲ್ಲಿ ನಗದು", expControl:"ಖರ್ಚು ನಿಯಂತ್ರಣ",
    invHealth:"ಸರಕು ಸ್ಥಿತಿ",
    newSale:"ಮಾರಾಟ ಸೇರಿಸಿ", newInvoice:"ಬಿಲ್ ಮಾಡಿ",
    addEntry:"ನಮೂದು ಸೇರಿಸಿ", addItem:"+ ಸರಕು ಸೇರಿಸಿ",
    save:"ಉಳಿಸಿ", cancel:"ಹಿಂತಿರುಗಿ", print:"ಮುದ್ರಿಸಿ",
    whatsapp:"WhatsApp ನಲ್ಲಿ ಕಳುಹಿಸಿ", markPaid:"ಹಣ ಬಂತು",
    remind:"ನೆನಪಿಸಿ",
    customer:"ಗ್ರಾಹಕ", amount:"ಮೊತ್ತ ₹", date:"ದಿನಾಂಕ",
    total:"ಒಟ್ಟು", qty:"ಎಷ್ಟು", rate:"ಬೆಲೆ",
    grandTotal:"ಒಟ್ಟು ಮೊತ್ತ", cashIn:"ನಗದು ಬಂತು",
    cashOut:"ನಗದು ಹೋಯಿತು", openingBal:"ಶುರುವಿನ ನಗದು",
    closingBal:"ಉಳಿದ ನಗದು",
    noSales:"ಇನ್ನೂ ಮಾರಾಟ ಇಲ್ಲ!",
    noExpenses:"ಇನ್ನೂ ಖರ್ಚು ಇಲ್ಲ",
    noItems:"ಸರಕು ಸೇರಿಸಿಲ್ಲ!",
    loading:"ನಿರೀಕ್ಷಿಸಿ...", saved:"ಉಳಿಸಲಾಯಿತು!",
    goodMorning:"ನಮಸ್ಕಾರ",
    salesEntry:"ಮಾರಾಟ ನಮೂದು", totalSalesLabel:"ಒಟ್ಟು ಮಾರಾಟ", numSalesLabel:"ಒಟ್ಟು ಮಾರಾಟ ಸಂಖ್ಯೆ", optional:"(ಐಚ್ಛಿಕ)", itemsLabel:"ಸರಕು", notesPlaceholder:"ಈ ಮಾರಾಟದ ಬಗ್ಗೆ ಬರೆಯಿರಿ", saving:"ಉಳಿಸುತ್ತಿದೆ...", searchCustomerPh:"ಗ್ರಾಹಕರ ಹೆಸರಿನಿಂದ ಹುಡುಕಿ", confirmDeleteSale:"ಈ ಮಾರಾಟವನ್ನು ತೆಗೆಯಬೇಕೆ?", deletedMsg:"ತೆಗೆಯಲಾಗಿದೆ!", errorMsg:"ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", walkIn:"ನೇರ ಗ್ರಾಹಕ", itemNamePh:"ಸರಕಿನ ಹೆಸರು", pricePh:"ಬೆಲೆ", noSalesEmptyMsg:"ಇನ್ನೂ ಮಾರಾಟ ಇಲ್ಲ. ಮೇಲೆ ಮೊದಲ ಮಾರಾಟ ಸೇರಿಸಿ.",
    notes:"ಟಿಪ್ಪಣಿ",
    noRecordsYet:"ಇನ್ನೂ ಏನೂ ಇಲ್ಲ", editItem:"ಬದಲಿಸಿ", addNew:"+ ಸೇರಿಸಿ", update:"ಅಪ್‌ಡೇಟ್ ಮಾಡಿ",
    askPlaceholder:"ನಿಮ್ಮ ವ್ಯವಹಾರದ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ...",
    salesThisMonth:"ಈ ತಿಂಗಳ ಮಾರಾಟ", estProfit:"ಅಂದಾಜು ಲಾಭ",
    inProfitMsg:"ನೀವು ಲಾಭದಲ್ಲಿದ್ದೀರಿ", notProfitMsg:"ಖರ್ಚು ಗಳಿಕೆಗಿಂತ ಹೆಚ್ಚು",
    transactionsWord:"ಮಾರಾಟ ಆಯಿತು", stockItemsWord:"ಸರಕು ಸ್ಟಾಕ್‌ನಲ್ಲಿ",
    analysing:"ಪರಿಶೀಲಿಸುತ್ತಿದ್ದೇವೆ...", lowStockMsg:"ಸರಕು ಕಡಿಮೆಯಾಗುತ್ತಿದೆ",
    view:"ನೋಡಿ", updateStock:"ಸ್ಟಾಕ್ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ", logExpense:"ಖರ್ಚು ಬರೆಯಿರಿ",
    addCustomer:"ಗ್ರಾಹಕ ಸೇರಿಸಿ", payment:"ಪಾವತಿ ವಿಧಾನ",
    thisMonthSub:"ಈ ತಿಂಗಳು",
    welcome:"Business Vahi ಗೆ ಸ್ವಾಗತ",
    tagline:"ನಿಮ್ಮ ವ್ಯವಹಾರದ ಸರಳ ಲೆಕ್ಕ",
    startFree:"ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    login:"ಲಾಗಿನ್", signOut:"ಹೊರಹೋಗಿ",
    more:"ಇನ್ನಷ್ಟು", selectLanguage:"ಭಾಷೆ ಆರಿಸಿ",
    changeLanguage:"ಭಾಷೆ",
  },

  bn: {
    dashboard:"হোম", sales:"বিক্রয়", purchases:"কেনাকাটা",
    inventory:"মাল / স্টক", expenses:"খরচ", customers:"গ্রাহক",
    khata:"ধার খাতা", cashBook:"নগদ", gstInvoice:"বিল / রসিদ",
    gstReturns:"GST জমা", profitLoss:"লাভ ক্ষতি",
    balanceSheet:"হিসাব", aiAdvisor:"AI জিজ্ঞেস করুন",
    businessDashboard:"আমার ব্যবসা",
    thisMonth:"এই মাসে", estimatedPL:"আয়",
    fullPL:"সম্পূর্ণ বিবরণ", aiInsights:"AI পরামর্শ",
    recentSales:"সাম্প্রতিক বিক্রয়", allSales:"সব বিক্রয় দেখুন →",
    topProducts:"সবচেয়ে বেশি বিক্রিত মাল", salesChart:"বিক্রয় - ৩০ দিন",
    expensesChart:"এই মাসের খরচ", monthlySales:"৬ মাসের বিক্রয়",
    healthScore:"ব্যবসার স্কোর",
    revenue:"আয়", profit:"লাভ",
    netMargin:"লাভের শতাংশ", khataControl:"ধার দেওয়া",
    cashGen:"হাতে নগদ", expControl:"খরচ নিয়ন্ত্রণ",
    invHealth:"মালের অবস্থা",
    newSale:"বিক্রয় যোগ করুন", newInvoice:"বিল তৈরি করুন",
    addEntry:"এন্ট্রি যোগ করুন", addItem:"+ মাল যোগ করুন",
    save:"সেভ করুন", cancel:"ফিরে যান", print:"প্রিন্ট করুন",
    whatsapp:"WhatsApp এ পাঠান", markPaid:"টাকা পেয়েছি",
    remind:"মনে করিয়ে দিন",
    customer:"গ্রাহক", amount:"পরিমাণ ₹", date:"তারিখ",
    total:"মোট", qty:"কতটা", rate:"দাম",
    grandTotal:"মোট টাকা", cashIn:"নগদ পেয়েছি",
    cashOut:"নগদ দিয়েছি", openingBal:"শুরুর নগদ",
    closingBal:"বাকি নগদ",
    noSales:"এখনো বিক্রয় নেই!",
    noExpenses:"এখনো খরচ নেই",
    noItems:"মাল যোগ করা হয়নি!",
    loading:"অপেক্ষা করুন...", saved:"সেভ হয়েছে!",
    goodMorning:"নমস্কার",
    salesEntry:"বিক্রয় নথিভুক্ত করুন", totalSalesLabel:"মোট বিক্রয়", numSalesLabel:"মোট বিক্রয় সংখ্যা", optional:"(ঐচ্ছিক)", itemsLabel:"মাল", notesPlaceholder:"এই বিক্রয় সম্পর্কে লিখুন", saving:"সেভ হচ্ছে...", searchCustomerPh:"গ্রাহকের নাম দিয়ে খুঁজুন", confirmDeleteSale:"এই বিক্রয় মুছে ফেলবেন?", deletedMsg:"মুছে ফেলা হয়েছে!", errorMsg:"কিছু ভুল হয়েছে। আবার চেষ্টা করুন।", walkIn:"সরাসরি গ্রাহক", itemNamePh:"মালের নাম", pricePh:"দাম", noSalesEmptyMsg:"এখনো বিক্রয় নেই। উপরে প্রথম বিক্রয় যোগ করুন।",
    notes:"নোট",
    noRecordsYet:"এখনো কিছু নেই", editItem:"বদলান", addNew:"+ যোগ করুন", update:"আপডেট করুন",
    askPlaceholder:"আপনার ব্যবসা সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন...",
    salesThisMonth:"এই মাসে বিক্রয়", estProfit:"আনুমানিক লাভ",
    inProfitMsg:"আপনি লাভে আছেন", notProfitMsg:"খরচ আয়ের চেয়ে বেশি",
    transactionsWord:"বিক্রয় হয়েছে", stockItemsWord:"মাল স্টকে",
    analysing:"যাচাই করছি...", lowStockMsg:"মাল কমে যাচ্ছে",
    view:"দেখুন", updateStock:"স্টক আপডেট করুন", logExpense:"খরচ লিখুন",
    addCustomer:"গ্রাহক যোগ করুন", payment:"পেমেন্ট পদ্ধতি",
    thisMonthSub:"এই মাসে",
    welcome:"Business Vahi এ আপনাকে স্বাগতম",
    tagline:"আপনার ব্যবসার সহজ হিসাব",
    startFree:"বিনামূল্যে শুরু করুন",
    login:"লগইন", signOut:"বাইরে যান",
    more:"আরও", selectLanguage:"ভাষা বেছে নিন",
    changeLanguage:"ভাষা",
  },

  pa: {
    dashboard:"ਹੋਮ", sales:"ਵਿਕਰੀ", purchases:"ਖਰੀਦਦਾਰੀ",
    inventory:"ਮਾਲ / ਸਟਾਕ", expenses:"ਖਰਚਾ", customers:"ਗਾਹਕ",
    khata:"ਉਧਾਰ ਖਾਤਾ", cashBook:"ਨਕਦੀ", gstInvoice:"ਬਿੱਲ / ਰਸੀਦ",
    gstReturns:"GST ਭਰਨਾ", profitLoss:"ਨਫ਼ਾ ਨੁਕਸਾਨ",
    balanceSheet:"ਹਿਸਾਬ", aiAdvisor:"AI ਤੋਂ ਪੁੱਛੋ",
    businessDashboard:"ਮੇਰਾ ਕਾਰੋਬਾਰ",
    thisMonth:"ਇਸ ਮਹੀਨੇ", estimatedPL:"ਕਮਾਈ",
    fullPL:"ਪੂਰੀ ਜਾਣਕਾਰੀ", aiInsights:"AI ਸਲਾਹ",
    recentSales:"ਤਾਜ਼ੀ ਵਿਕਰੀ", allSales:"ਸਾਰੀ ਵਿਕਰੀ ਵੇਖੋ →",
    topProducts:"ਸਭ ਤੋਂ ਵੱਧ ਵਿਕਣ ਵਾਲਾ ਮਾਲ", salesChart:"ਵਿਕਰੀ - 30 ਦਿਨ",
    expensesChart:"ਇਸ ਮਹੀਨੇ ਦਾ ਖਰਚਾ", monthlySales:"6 ਮਹੀਨੇ ਦੀ ਵਿਕਰੀ",
    healthScore:"ਕਾਰੋਬਾਰ ਦਾ ਸਕੋਰ",
    revenue:"ਆਮਦਨ", profit:"ਨਫ਼ਾ",
    netMargin:"ਨਫ਼ੇ ਦੀ ਪ੍ਰਤੀਸ਼ਤ", khataControl:"ਉਧਾਰ ਦਿੱਤਾ",
    cashGen:"ਹੱਥ ਵਿੱਚ ਨਕਦੀ", expControl:"ਖਰਚਾ ਕੰਟਰੋਲ",
    invHealth:"ਮਾਲ ਦੀ ਸਥਿਤੀ",
    newSale:"ਵਿਕਰੀ ਜੋੜੋ", newInvoice:"ਬਿੱਲ ਬਣਾਓ",
    addEntry:"ਐਂਟਰੀ ਜੋੜੋ", addItem:"+ ਮਾਲ ਜੋੜੋ",
    save:"ਸੇਵ ਕਰੋ", cancel:"ਵਾਪਸ ਜਾਓ", print:"ਪ੍ਰਿੰਟ ਕਰੋ",
    whatsapp:"WhatsApp ਤੇ ਭੇਜੋ", markPaid:"ਪੈਸੇ ਮਿਲ ਗਏ",
    remind:"ਯਾਦ ਕਰਾਓ",
    customer:"ਗਾਹਕ", amount:"ਰਕਮ ₹", date:"ਤਾਰੀਖ",
    total:"ਕੁੱਲ", qty:"ਕਿੰਨਾ", rate:"ਭਾਅ",
    grandTotal:"ਕੁੱਲ ਰਕਮ", cashIn:"ਨਕਦੀ ਮਿਲੀ",
    cashOut:"ਨਕਦੀ ਦਿੱਤੀ", openingBal:"ਸ਼ੁਰੂ ਦੀ ਨਕਦੀ",
    closingBal:"ਬਾਕੀ ਨਕਦੀ",
    noSales:"ਅਜੇ ਵਿਕਰੀ ਨਹੀਂ!",
    noExpenses:"ਅਜੇ ਖਰਚਾ ਨਹੀਂ",
    noItems:"ਮਾਲ ਨਹੀਂ ਜੋੜਿਆ!",
    loading:"ਰੁਕੋ...", saved:"ਸੇਵ ਹੋ ਗਿਆ!",
    goodMorning:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
    salesEntry:"ਵਿਕਰੀ ਦਰਜ ਕਰੋ", totalSalesLabel:"ਕੁੱਲ ਵਿਕਰੀ", numSalesLabel:"ਕੁੱਲ ਵਿਕਰੀ ਗਿਣਤੀ", optional:"(ਵਿਕਲਪਿਕ)", itemsLabel:"ਮਾਲ", notesPlaceholder:"ਇਸ ਵਿਕਰੀ ਬਾਰੇ ਕੁਝ ਲਿਖੋ", saving:"ਸੇਵ ਹੋ ਰਿਹਾ ਹੈ...", searchCustomerPh:"ਗਾਹਕ ਦੇ ਨਾਮ ਨਾਲ ਖੋਜੋ", confirmDeleteSale:"ਕੀ ਇਹ ਵਿਕਰੀ ਹਟਾਉਣੀ ਹੈ?", deletedMsg:"ਹਟਾ ਦਿੱਤਾ!", errorMsg:"ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।", walkIn:"ਸਿੱਧਾ ਗਾਹਕ", itemNamePh:"ਮਾਲ ਦਾ ਨਾਮ", pricePh:"ਭਾਅ", noSalesEmptyMsg:"ਅਜੇ ਵਿਕਰੀ ਨਹੀਂ। ਉੱਪਰ ਪਹਿਲੀ ਵਿਕਰੀ ਜੋੜੋ।",
    notes:"ਨੋਟ",
    noRecordsYet:"ਅਜੇ ਕੁਝ ਨਹੀਂ", editItem:"ਬਦਲੋ", addNew:"+ ਜੋੜੋ", update:"ਅੱਪਡੇਟ ਕਰੋ",
    askPlaceholder:"ਆਪਣੇ ਕਾਰੋਬਾਰ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ...",
    salesThisMonth:"ਇਸ ਮਹੀਨੇ ਵਿਕਰੀ", estProfit:"ਅਨੁਮਾਨਿਤ ਨਫ਼ਾ",
    inProfitMsg:"ਤੁਸੀਂ ਨਫ਼ੇ ਵਿੱਚ ਹੋ", notProfitMsg:"ਖਰਚਾ ਕਮਾਈ ਤੋਂ ਵੱਧ ਹੈ",
    transactionsWord:"ਵਿਕਰੀ ਹੋਈ", stockItemsWord:"ਮਾਲ ਸਟਾਕ ਵਿੱਚ",
    analysing:"ਜਾਂਚ ਰਹੇ ਹਾਂ...", lowStockMsg:"ਮਾਲ ਘਟ ਰਿਹਾ ਹੈ",
    view:"ਵੇਖੋ", updateStock:"ਸਟਾਕ ਅੱਪਡੇਟ ਕਰੋ", logExpense:"ਖਰਚਾ ਲਿਖੋ",
    addCustomer:"ਗਾਹਕ ਜੋੜੋ", payment:"ਭੁਗਤਾਨ ਢੰਗ",
    thisMonthSub:"ਇਸ ਮਹੀਨੇ",
    welcome:"Business Vahi ਵਿੱਚ ਜੀ ਆਇਆਂ",
    tagline:"ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਦਾ ਆਸਾਨ ਹਿਸਾਬ",
    startFree:"ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ",
    login:"ਲੌਗਿਨ", signOut:"ਬਾਹਰ ਜਾਓ",
    more:"ਹੋਰ", selectLanguage:"ਭਾਸ਼ਾ ਚੁਣੋ",
    changeLanguage:"ਭਾਸ਼ਾ",
  },

  ml: {
    dashboard:"ഹോം", sales:"വിൽക്കൽ", purchases:"വാങ്ങൽ",
    inventory:"സ്റ്റോക്ക്", expenses:"ചെലവ്", customers:"ഉപഭോക്താക്കൾ",
    khata:"കടം ബുക്ക്", cashBook:"പണം", gstInvoice:"ബിൽ / രസീത്",
    gstReturns:"GST ഫയൽ", profitLoss:"ലാഭ നഷ്ടം",
    balanceSheet:"കണക്ക്", aiAdvisor:"AI ചോദിക്കൂ",
    businessDashboard:"എന്റെ ബിസിനസ്",
    thisMonth:"ഈ മാസം", estimatedPL:"വരുമാനം",
    fullPL:"പൂർണ്ണ വിവരം", aiInsights:"AI നിർദ്ദേശം",
    recentSales:"സമീപകാല വിൽക്കൽ", allSales:"എല്ലാ വിൽക്കൽ →",
    topProducts:"കൂടുതൽ വിറ്റ സാധനങ്ങൾ", salesChart:"വിൽക്കൽ - 30 ദിവസം",
    expensesChart:"ഈ മാസം ചെലവ്", monthlySales:"6 മാസ വിൽക്കൽ",
    healthScore:"ബിസിനസ് സ്കോർ",
    revenue:"വരുമാനം", profit:"ലാഭം",
    netMargin:"ലാഭ ശതമാനം", khataControl:"കടം കൊടുത്തത്",
    cashGen:"കൈയ്യിൽ പണം", expControl:"ചെലവ് നിയന്ത്രണം",
    invHealth:"സ്റ്റോക്ക് നില",
    newSale:"വിൽക്കൽ ചേർക്കൂ", newInvoice:"ബിൽ ഉണ്ടാക്കൂ",
    addEntry:"എൻട്രി ചേർക്കൂ", addItem:"+ സ്റ്റോക്ക് ചേർക്കൂ",
    save:"സേവ് ചെയ്യൂ", cancel:"തിരിച്ചു പോകൂ", print:"പ്രിന്റ് ചെയ്യൂ",
    whatsapp:"WhatsApp ൽ അയക്കൂ", markPaid:"പണം കിട്ടി",
    remind:"ഓർമ്മിപ്പിക്കൂ",
    customer:"ഉപഭോക്താവ്", amount:"തുക ₹", date:"തീയതി",
    total:"ആകെ", qty:"എത്ര", rate:"വില",
    grandTotal:"ആകെ തുക", cashIn:"പണം കിട്ടി",
    cashOut:"പണം കൊടുത്തു", openingBal:"തുടക്ക പണം",
    closingBal:"ബാക്കി പണം",
    noSales:"ഇതുവരെ വിൽക്കൽ ഇല്ല!",
    noExpenses:"ഇതുവരെ ചെലവ് ഇല്ല",
    noItems:"സ്റ്റോക്ക് ചേർത്തിട്ടില്ല!",
    loading:"കാത്തിരിക്കൂ...", saved:"സേവ് ആയി!",
    goodMorning:"നമസ്കാരം",
    salesEntry:"വിൽക്കൽ രേഖപ്പെടുത്തുക", totalSalesLabel:"ആകെ വിൽക്കൽ", numSalesLabel:"ആകെ വിൽക്കൽ എണ്ണം", optional:"(ഐച്ഛികം)", itemsLabel:"സാധനങ്ങൾ", notesPlaceholder:"ഈ വിൽക്കലിനെക്കുറിച്ച് എഴുതുക", saving:"സേവ് ചെയ്യുന്നു...", searchCustomerPh:"ഉപഭോക്താവിന്റെ പേരിൽ തിരയുക", confirmDeleteSale:"ഈ വിൽക്കൽ നീക്കണോ?", deletedMsg:"നീക്കി!", errorMsg:"എന്തോ തെറ്റ് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക.", walkIn:"നേരിട്ടുള്ള ഉപഭോക്താവ്", itemNamePh:"സാധനത്തിന്റെ പേര്", pricePh:"വില", noSalesEmptyMsg:"ഇതുവരെ വിൽക്കൽ ഇല്ല. മുകളിൽ ആദ്യ വിൽക്കൽ ചേർക്കുക.",
    notes:"കുറിപ്പ്",
    noRecordsYet:"ഇതുവരെ ഒന്നുമില്ല", editItem:"മാറ്റുക", addNew:"+ ചേർക്കുക", update:"അപ്ഡേറ്റ് ചെയ്യുക",
    askPlaceholder:"നിങ്ങളുടെ ബിസിനസ്സിനെക്കുറിച്ച് എന്തും ചോദിക്കൂ...",
    salesThisMonth:"ഈ മാസ വിൽക്കൽ", estProfit:"കണക്കാക്കിയ ലാഭം",
    inProfitMsg:"നിങ്ങൾ ലാഭത്തിലാണ്", notProfitMsg:"ചെലവ് വരുമാനത്തേക്കാൾ കൂടുതൽ",
    transactionsWord:"വിൽക്കൽ നടന്നു", stockItemsWord:"സാധനങ്ങൾ സ്റ്റോക്കിൽ",
    analysing:"പരിശോധിക്കുന്നു...", lowStockMsg:"സാധനം കുറയുന്നു",
    view:"കാണുക", updateStock:"സ്റ്റോക്ക് അപ്ഡേറ്റ് ചെയ്യുക", logExpense:"ചെലവ് എഴുതുക",
    addCustomer:"ഉപഭോക്താവിനെ ചേർക്കുക", payment:"പണം കൊടുക്കുന്ന രീതി",
    thisMonthSub:"ഈ മാസം",
    welcome:"Business Vahi ലേക്ക് സ്വാഗതം",
    tagline:"നിങ്ങളുടെ ബിസിനസ്സിന്റെ ലളിതമായ കണക്ക്",
    startFree:"സൗജന്യമായി ആരംഭിക്കൂ",
    login:"ലോഗിൻ", signOut:"പുറത്തു പോകൂ",
    more:"കൂടുതൽ", selectLanguage:"ഭാഷ തിരഞ്ഞെടുക്കൂ",
    changeLanguage:"ഭാഷ",
  },

  or: {
    dashboard:"ହୋମ", sales:"ବିକ୍ରୟ", purchases:"କ୍ରୟ",
    inventory:"ମାଲ / ଷ୍ଟକ", expenses:"ଖର୍ଚ୍ଚ", customers:"ଗ୍ରାହକ",
    khata:"ଉଧାର ଖାତା", cashBook:"ନଗଦ", gstInvoice:"ବିଲ / ରସିଦ",
    gstReturns:"GST ଦାଖଲ", profitLoss:"ଲାଭ କ୍ଷତି",
    balanceSheet:"ହିସାବ", aiAdvisor:"AI ପଚାରନ୍ତୁ",
    businessDashboard:"ମୋ ବ୍ୟବସାୟ",
    thisMonth:"ଏ ମାସ", estimatedPL:"ଉପାର୍ଜନ",
    fullPL:"ସମ୍ପୂର୍ଣ୍ଣ ବିବରଣ", aiInsights:"AI ପରାମର୍ଶ",
    recentSales:"ସାମ୍ପ୍ରତିକ ବିକ୍ରୟ", allSales:"ସବୁ ବିକ୍ରୟ →",
    topProducts:"ଅଧିକ ବିକ୍ରି ମାଲ", salesChart:"ବିକ୍ରୟ - 30 ଦିନ",
    expensesChart:"ଏ ମାସ ଖର୍ଚ୍ଚ", monthlySales:"6 ମାସ ବିକ୍ରୟ",
    healthScore:"ବ୍ୟବସାୟ ସ୍କୋର",
    revenue:"ଆୟ", profit:"ଲାଭ",
    netMargin:"ଲାଭ ପ୍ରତିଶତ", khataControl:"ଉଧାର ଦେଲି",
    cashGen:"ହାତରେ ନଗଦ", expControl:"ଖର୍ଚ୍ଚ ନିୟନ୍ତ୍ରଣ",
    invHealth:"ମାଲ ଅବସ୍ଥା",
    newSale:"ବିକ୍ରୟ ଯୋଡ଼ନ୍ତୁ", newInvoice:"ବିଲ ତିଆରି",
    addEntry:"ଏଣ୍ଟ୍ରି ଯୋଡ଼ନ୍ତୁ", addItem:"+ ମାଲ ଯୋଡ଼ନ୍ତୁ",
    save:"ସେଭ କରନ୍ତୁ", cancel:"ଫେରନ୍ତୁ", print:"ପ୍ରିଣ୍ଟ",
    whatsapp:"WhatsApp ରେ ପଠାନ୍ତୁ", markPaid:"ଟଙ୍କା ମିଳିଲା",
    remind:"ମନେ କରାନ୍ତୁ",
    customer:"ଗ୍ରାହକ", amount:"ରାଶି ₹", date:"ତାରିଖ",
    total:"ମୋଟ", qty:"କେତେ", rate:"ଦର",
    grandTotal:"ମୋଟ ରାଶି", cashIn:"ନଗଦ ମିଳିଲା",
    cashOut:"ନଗଦ ଦେଲି", openingBal:"ଆରମ୍ଭ ନଗଦ",
    closingBal:"ବଳକା ନଗଦ",
    noSales:"ଏ ପର୍ଯ୍ୟନ୍ତ ବିକ୍ରୟ ନାହିଁ!",
    noExpenses:"ଏ ପର୍ଯ୍ୟନ୍ତ ଖର୍ଚ୍ଚ ନାହିଁ",
    noItems:"ମାଲ ଯୋଡ଼ା ହୋଇ ନାହିଁ!",
    loading:"ଅପେକ୍ଷା କରନ୍ତୁ...", saved:"ସେଭ ହୋଇଗଲା!",
    goodMorning:"ନମସ୍କାର",
    salesEntry:"ବିକ୍ରୟ ପ୍ରବେଶ", totalSalesLabel:"ମୋଟ ବିକ୍ରୟ", numSalesLabel:"ମୋଟ ବିକ୍ରୟ ସଂଖ୍ୟା", optional:"(ଇଚ୍ଛାଧୀନ)", itemsLabel:"ମାଲ", notesPlaceholder:"ଏ ବିକ୍ରୟ ବିଷୟରେ କିଛି ଲେଖନ୍ତୁ", saving:"ସେଭ ହେଉଛି...", searchCustomerPh:"ଗ୍ରାହକଙ୍କ ନାମରେ ଖୋଜନ୍ତୁ", confirmDeleteSale:"ଏ ବିକ୍ରୟ ହଟାଇବେ କି?", deletedMsg:"ହଟାଗଲା!", errorMsg:"କିଛି ଭୁଲ ହେଲା। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।", walkIn:"ସିଧା ଗ୍ରାହକ", itemNamePh:"ମାଲର ନାମ", pricePh:"ଦର", noSalesEmptyMsg:"ଏ ପର୍ଯ୍ୟନ୍ତ ବିକ୍ରୟ ନାହିଁ। ଉପରେ ପ୍ରଥମ ବିକ୍ରୟ ଯୋଡ଼ନ୍ତୁ।",
    notes:"ଟିପ୍ପଣୀ",
    noRecordsYet:"ଏ ପର୍ଯ୍ୟନ୍ତ କିଛି ନାହିଁ", editItem:"ବଦଳାନ୍ତୁ", addNew:"+ ଯୋଡ଼ନ୍ତୁ", update:"ଅପଡେଟ କରନ୍ତୁ",
    askPlaceholder:"ଆପଣଙ୍କ ବ୍ୟବସାୟ ବିଷୟରେ କିଛି ପଚାରନ୍ତୁ...",
    salesThisMonth:"ଏ ମାସ ବିକ୍ରୟ", estProfit:"ଆକଳିତ ଲାଭ",
    inProfitMsg:"ଆପଣ ଲାଭରେ ଅଛନ୍ତି", notProfitMsg:"ଖର୍ଚ୍ଚ ରୋଜଗାରଠାରୁ ଅଧିକ",
    transactionsWord:"ବିକ୍ରୟ ହେଲା", stockItemsWord:"ମାଲ ଷ୍ଟକରେ",
    analysing:"ଯାଞ୍ଚ କରୁଛୁ...", lowStockMsg:"ମାଲ କମି ଯାଉଛି",
    view:"ଦେଖନ୍ତୁ", updateStock:"ଷ୍ଟକ ଅପଡେଟ କରନ୍ତୁ", logExpense:"ଖର୍ଚ୍ଚ ଲେଖନ୍ତୁ",
    addCustomer:"ଗ୍ରାହକ ଯୋଡ଼ନ୍ତୁ", payment:"ଦେୟ ପଦ୍ଧତି",
    thisMonthSub:"ଏ ମାସ",
    welcome:"Business Vahi କୁ ସ୍ୱାଗତ",
    tagline:"ଆପଣଙ୍କ ବ୍ୟବସାୟର ସହଜ ହିସାବ",
    startFree:"ମାଗଣାରେ ଆରମ୍ଭ କରନ୍ତୁ",
    login:"ଲଗଇନ", signOut:"ବାହାରକୁ ଯାନ୍ତୁ",
    more:"ଅଧିକ", selectLanguage:"ଭାଷା ବାଛନ୍ତୁ",
    changeLanguage:"ଭାଷା",
  },

  ur: {
    dashboard:"ہوم", sales:"فروخت", purchases:"خریداری",
    inventory:"مال / اسٹاک", expenses:"اخراجات", customers:"گاہک",
    khata:"ادھار کھاتہ", cashBook:"نقدی", gstInvoice:"بل / رسید",
    gstReturns:"GST جمع", profitLoss:"نفع نقصان",
    balanceSheet:"حساب", aiAdvisor:"AI سے پوچھیں",
    businessDashboard:"میرا کاروبار",
    thisMonth:"اس مہینے", estimatedPL:"کمائی",
    fullPL:"پوری تفصیل", aiInsights:"AI مشورہ",
    recentSales:"حالیہ فروخت", allSales:"تمام فروخت دیکھیں →",
    topProducts:"زیادہ بکنے والا مال", salesChart:"فروخت - 30 دن",
    expensesChart:"اس مہینے خرچ", monthlySales:"6 مہینے کی فروخت",
    healthScore:"کاروبار کا اسکور",
    revenue:"آمدنی", profit:"نفع",
    netMargin:"نفع کا فیصد", khataControl:"ادھار دیا",
    cashGen:"ہاتھ میں نقدی", expControl:"خرچ کنٹرول",
    invHealth:"مال کی حالت",
    newSale:"فروخت شامل کریں", newInvoice:"بل بنائیں",
    addEntry:"اندراج شامل کریں", addItem:"+ مال شامل کریں",
    save:"محفوظ کریں", cancel:"واپس جائیں", print:"پرنٹ کریں",
    whatsapp:"WhatsApp پر بھیجیں", markPaid:"پیسے مل گئے",
    remind:"یاد دہانی کریں",
    customer:"گاہک", amount:"رقم ₹", date:"تاریخ",
    total:"کل", qty:"کتنا", rate:"قیمت",
    grandTotal:"کل رقم", cashIn:"نقدی ملی",
    cashOut:"نقدی دی", openingBal:"شروع کی نقدی",
    closingBal:"باقی نقدی",
    noSales:"ابھی کوئی فروخت نہیں!",
    noExpenses:"ابھی کوئی خرچ نہیں",
    noItems:"مال شامل نہیں کیا!",
    loading:"انتظار کریں...", saved:"محفوظ ہو گیا!",
    goodMorning:"السلام علیکم",
    salesEntry:"فروخت درج کریں", totalSalesLabel:"کل فروخت", numSalesLabel:"کل فروخت کی تعداد", optional:"(اختیاری)", itemsLabel:"مال", notesPlaceholder:"اس فروخت کے بارے میں کچھ لکھیں", saving:"محفوظ ہو رہا ہے...", searchCustomerPh:"گاہک کے نام سے تلاش کریں", confirmDeleteSale:"کیا یہ فروخت حذف کریں؟", deletedMsg:"حذف ہو گیا!", errorMsg:"کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔", walkIn:"براہ راست گاہک", itemNamePh:"مال کا نام", pricePh:"قیمت", noSalesEmptyMsg:"ابھی کوئی فروخت نہیں۔ اوپر پہلی فروخت شامل کریں۔",
    notes:"نوٹ",
    noRecordsYet:"ابھی کچھ نہیں", editItem:"تبدیل کریں", addNew:"+ شامل کریں", update:"اپ ڈیٹ کریں",
    askPlaceholder:"اپنے کاروبار کے بارے میں کچھ بھی پوچھیں...",
    salesThisMonth:"اس مہینے فروخت", estProfit:"تخمینی نفع",
    inProfitMsg:"آپ نفع میں ہیں", notProfitMsg:"خرچ کمائی سے زیادہ ہے",
    transactionsWord:"فروخت ہوئی", stockItemsWord:"مال اسٹاک میں",
    analysing:"جانچ رہے ہیں...", lowStockMsg:"مال کم ہو رہا ہے",
    view:"دیکھیں", updateStock:"اسٹاک اپ ڈیٹ کریں", logExpense:"خرچ لکھیں",
    addCustomer:"گاہک شامل کریں", payment:"ادائیگی کا طریقہ",
    thisMonthSub:"اس مہینے",
    welcome:"Business Vahi میں خوش آمدید",
    tagline:"آپ کے کاروبار کا آسان حساب",
    startFree:"مفت شروع کریں",
    login:"لاگ ان", signOut:"باہر جائیں",
    more:"مزید", selectLanguage:"زبان چنیں",
    changeLanguage:"زبان",
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem("fintr-lang") || "en"; } catch { return "en"; }
  });

  const setLanguage = (code) => {
    setLang(code);
    try { localStorage.setItem("fintr-lang", code); } catch {}
  };

  const t = (key) => T[lang]?.[key] || T.en?.[key] || key;
  const isRTL = lang === "ur";
  const isHindi = lang === "hi";
  const currentLang = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];

  return (
    <LangContext.Provider value={{ lang, setLanguage, t, isHindi, isRTL, currentLang, LANGUAGES }}>
      <div dir={isRTL ? "rtl" : "ltr"}>
        {children}
      </div>
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
