// Business Vahi Business Categories
// Each category customizes: units, expense types, GST rates, sample products

export const BUSINESS_CATEGORIES = [
  {
    id: "grocery",
    label: "Grocery / Kirana",
    icon: "🛒",
    desc: "Kirana store, supermarket, provisions",
    color: "#16a34a",
    units: ["kg", "g", "litre", "ml", "pcs", "packet", "bag", "box", "dozen", "quintal"],
    expense_cats: ["Raw Material Purchase", "Rent", "Salary", "Electricity", "Transport", "Packaging", "Other"],
    gst_rates: [0, 5, 12, 18],
    sample_products: [
      "Basmati Rice 1kg", "Toor Dal 1kg", "Sugar 1kg",
      "Cooking Oil 1L", "Wheat Flour 1kg", "Salt 1kg", "Tea 250g",
    ],
    invoice_note: "Thank you for shopping with us!",
  },
  {
    id: "medical",
    label: "Medical / Pharmacy",
    icon: "💊",
    desc: "Pharmacy, chemist, medical store",
    color: "#dc2626",
    units: ["strip", "bottle", "vial", "tube", "box", "pcs", "ml", "tablet", "capsule"],
    expense_cats: ["Medicine Purchase", "Rent", "Salary", "Electricity", "Refrigeration", "License Fees", "Other"],
    gst_rates: [0, 5, 12],
    sample_products: [
      "Paracetamol 500mg", "Amoxicillin 500mg", "Vitamin C 500mg",
      "Antacid Tablet", "Cough Syrup 100ml", "Bandage Roll",
    ],
    invoice_note: "Medicines cannot be returned. Keep out of reach of children.",
    extra_note: "Track batch number and expiry date in product notes.",
  },
  {
    id: "clothing",
    label: "Clothing / Fashion",
    icon: "👗",
    desc: "Readymade clothes, textiles, fashion",
    color: "#7c3aed",
    units: ["pcs", "metre", "set", "pair", "dozen", "roll"],
    expense_cats: ["Stock Purchase", "Rent", "Salary", "Electricity", "Packaging", "Tailoring Cost", "Other"],
    gst_rates: [5, 12, 18],
    sample_products: [
      "Cotton Shirt", "Formal Trouser", "Saree", "Kurta Pyjama",
      "T-Shirt", "Jeans", "Salwar Suit",
    ],
    invoice_note: "Goods once sold will not be exchanged without bill.",
  },
  {
    id: "stationery",
    label: "Stationery / Books",
    icon: "📚",
    desc: "Stationery shop, bookstore, office supplies",
    color: "#0284c7",
    units: ["pcs", "box", "dozen", "pack", "ream", "set", "roll"],
    expense_cats: ["Stock Purchase", "Rent", "Salary", "Electricity", "Transport", "Other"],
    gst_rates: [0, 5, 12, 18],
    sample_products: [
      "Notebook A4", "Ball Pen Blue", "Pencil HB",
      "Eraser", "Geometry Box", "File Folder", "Stapler",
    ],
    invoice_note: "Thank you for your purchase!",
  },
  {
    id: "electronics",
    label: "Electronics / Mobile",
    icon: "📱",
    desc: "Mobile shop, electronics, repairs",
    color: "#d97706",
    units: ["pcs", "set", "box", "unit"],
    expense_cats: ["Stock Purchase", "Rent", "Salary", "Electricity", "Repair Parts", "Service Tools", "Other"],
    gst_rates: [12, 18, 28],
    sample_products: [
      "Mobile Phone", "Charger", "Earphones",
      "Screen Guard", "Mobile Cover", "Power Bank", "Data Cable",
    ],
    invoice_note: "Warranty as per manufacturer terms. No cash refund.",
  },
  {
    id: "restaurant",
    label: "Restaurant / Food",
    icon: "🍽️",
    desc: "Restaurant, dhaba, tiffin service, bakery",
    color: "#ea580c",
    units: ["plate", "kg", "litre", "pcs", "box", "packet", "portion"],
    expense_cats: ["Raw Materials", "Rent", "Salary", "Electricity", "Gas / LPG", "Packaging", "Cleaning", "Other"],
    gst_rates: [5, 18],
    sample_products: [
      "Thali (Veg)", "Thali (Non-Veg)", "Rice Bowl",
      "Dal Roti", "Tea", "Coffee", "Cold Drink",
    ],
    invoice_note: "Thank you for dining with us! Please visit again.",
  },
  {
    id: "hardware",
    label: "Hardware / Building",
    icon: "🔧",
    desc: "Hardware store, building materials, tools",
    color: "#64748b",
    units: ["pcs", "kg", "metre", "bag", "litre", "box", "set", "foot", "sqft"],
    expense_cats: ["Stock Purchase", "Rent", "Salary", "Electricity", "Transport / Loading", "Other"],
    gst_rates: [12, 18, 28],
    sample_products: [
      "Cement 50kg", "Sand (per bag)", "PVC Pipe", "Paint 20L",
      "Nails 1kg", "Wire (per metre)", "Plywood Sheet",
    ],
    invoice_note: "Goods once sold will not be taken back.",
  },
  {
    id: "salon",
    label: "Salon / Beauty",
    icon: "💇",
    desc: "Hair salon, beauty parlour, spa",
    color: "#db2777",
    units: ["service", "pcs", "ml", "bottle", "session"],
    expense_cats: ["Products Purchase", "Rent", "Salary", "Electricity", "Equipment", "Water", "Other"],
    gst_rates: [5, 18],
    sample_products: [
      "Haircut (Men)", "Haircut (Women)", "Hair Color",
      "Facial", "Manicure", "Pedicure", "Waxing",
    ],
    invoice_note: "Thank you for visiting us! Book your next appointment.",
  },
  {
    id: "freelancer",
    label: "Freelancer / Consultant",
    icon: "💼",
    desc: "IT, design, consulting, teaching, services",
    color: "#0A0A0A",
    units: ["hour", "project", "month", "day", "session", "pcs"],
    expense_cats: ["Software / Tools", "Internet", "Marketing", "Equipment", "Travel", "Training", "Other"],
    gst_rates: [0, 18],
    sample_products: [
      "Web Development", "App Development", "Graphic Design",
      "Consulting Session", "Training", "Content Writing",
    ],
    invoice_note: "Payment due within 15 days of invoice date.",
  },
  {
    id: "other",
    label: "Other Business",
    icon: "🏪",
    desc: "Any other type of business",
    color: "#374151",
    units: ["pcs", "kg", "litre", "service", "box", "set", "metre"],
    expense_cats: ["Purchase", "Rent", "Salary", "Electricity", "Transport", "Marketing", "Other"],
    gst_rates: [0, 5, 12, 18, 28],
    sample_products: [],
    invoice_note: "Thank you for your business!",
  },
];

export const getCategoryById = (id) =>
  BUSINESS_CATEGORIES.find((c) => c.id === id) || BUSINESS_CATEGORIES[BUSINESS_CATEGORIES.length - 1];
